Python/PythonII/DjangoII/Multi_Apps/Multi_Apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^course/', include('apps.courseapp.urls', namespace="course")),
    url(r'^', include('apps.loginapp.urls', namespace="login")),
]

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/urls.py
from django.conf.urls import url, include
from views import index, create, remove_Course, remove, infoPage, commentPost, commentDelete, user_courses, add_user_courses

app_name = 'course'
urlpatterns = [
    url(r'^$', index, name= 'index'),
    url(r'^create$', create, name= 'create'),
    url(r'^user_courses', user_courses, name='user_courses'),
    url(r'^add_user_courses', add_user_courses, name='add_user_courses'),
    url(r'^remove_Course/(?P<id>\d+)$', remove_Course, name= 'remove_Course'),
    url(r'^remove_Course/delete/remove/(?P<id>\d+)$',remove, name= 'delete'),
    url(r'^courseInfo/(?P<id>\d+)$',infoPage, name= 'courseInfo'),
    url(r'^courseInfo/commentPost/(?P<id>\d+)$', commentPost, name= 'commentPost'),
    url(r'^commentDelete/(?P<id>\d+)$', commentDelete, name= 'commentDelete'),



]

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/models.py
from __future__ import unicode_literals

from django.db import models
from ..loginapp.models import User

# Create your models here.

class Course(models.Model):
    name = models.CharField(max_length= 255)
    description = models.TextField()
    count= models.IntegerField(default =0)
    user = models.ForeignKey(User, related_name="courses")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __unicode__(self):
        return unicode(self.id)+" "+self.name + " "+ self.description +" "+ unicode(self.user)+" "+unicode(self.count)


# optional comments section not completed..

class Comment(models.Model):
    comment = models.TextField()
    user = models.ForeignKey(User, related_name="comments")
    courses = models.ForeignKey(Course, related_name="course_comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.comment+" "


#building models for course..

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/views.py
from django.shortcuts import render, redirect
from .models import Course, Comment
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
    info = {
    'courses': Course.objects.filter(user_id=request.session['id']),
    'logs': Course.objects.all(),
    }
    # print info
    return render(request, 'courseapp/index.html', info)

def create(request):
    # print request.POST['name']
    # print request.POST['description']
    Course.objects.create(user_id= request.session['id'], name =request.POST['name'] , description =request.POST['description'],)
    return redirect('course:index')

def remove_Course(request, id):
    info = {
    'ids': Course.objects.filter(id=id)
    }
    return render(request, 'courseapp/remove.html', info)

def remove(request,id):
    instance = Course.objects.get(id=id)
    instance.delete()
    return redirect(reverse('course:index'))


def infoPage(request,id):
    info = {
    'courses': Course.objects.filter(id=id),
    'text': Comment.objects.all(),
    }
    # print info
    return render(request, 'courseapp/info.html', info)


def commentPost(request,id):
    course = Course.objects.get(id=id)
    # print course,"<----"
    # print course.id, "id??"
    # print course
    Comment.objects.create(comment=request.POST['comment'], courses_id=course.id, user_id=request.session['id'] )
    return redirect('course:index')
    # return redirect (reverse('course:commentPost', kwargs={'id':course.id}))

def commentDelete(request, id):
    delete = Comment.objects.get(id=id)
    delete.delete()
    return redirect ('course:index')

def user_courses(request):
    data={
    'users': Course.objects.all()
    }
    # print data
    return render (request, 'courseapp/user_courses.html', data )

def add_user_courses(request):
    request.session['count'] = 0
    tally = Course.objects.get(user_id__email=request.POST['student'])
    print tally, "????"
    if request.method == 'POST':
        # Course.objects.create(user_id= tally.id, count= +1)


        return redirect('course:user_courses')

#need to look up the redirect to include the id so I dont have to redirect to the main index page.

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/templates/courseapp/index.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <!-- <title>Courses</title> -->
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'courseapp/css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'courseapp/css/style.css' %}">
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="title col-md-6">
               <h3>Add New Courses</h3>
               <h5>ID:{{request.session.id}}</h5>
               <h5>User: {{request.session.email}}</h5>
               <h5>Name: {{request.session.name}}</h5>
               <br>
               <form action="{% url 'course:create' %}" method="post">
                 {% csrf_token %}
                 <label> Course Name: </label><input type="text" name="name" />
                 <label>Description: </label>
                 <textarea name="description" rows="8" cols="80"></textarea>
                 <input type="submit" value="Add" />
               </form>
            </div>
            <div class="form col-md-6">
               List of Courses:
               {% for log in logs %}
                  <ul>
                     <li>{{log.name}}</li>
                  </ul>
               {% endfor %}
            </div>
         </div>
         <br>
            <div class="row">
               <div class="table col">
                  <table>
                     <tr>
                        <th>ID</th>
                        <th>Course Name</th>
                        <th>Description</th>
                        <th>Date Added</th>
                        <th>Actions</th>
                     </tr>
                     {% for course in courses %}
                     <tr>
                        <td>{{course.id}}</td>
                        <td>{{course.name}}</td>
                        <td>
                        <a href="courseInfo/{{course.id}}">See Course Description/ Add Comments</a>
                        </td>
                        <!-- <td>{{course.description}}</td> -->
                        <td>{{course.created_at}}</td>
                        <td>
                        <a href="/course/remove_Course/{{course.id}}">Remove</a>
                        </td>
                     </tr>
                     {% endfor %}
                  </table>
                  <hr>
               </div>
            </div>
            <div class="row">
               <a href="{% url 'login:success' %}">Back to Dashboard Page</a>
            </div>
      </div>
   </body>
</html>

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/templates/courseapp/info.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Course Description</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'courseapp/css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'courseapp/css/style.css' %}">
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="header col">
         {% for course in courses %}
               <h2><u>Course Info!</u></h3>
               <h4>Name: {{course.name}} </h4>
               <h4>Description: {{course.description}} </h4>
            </div>
         </div>
         <hr>
         <div class="comments">
            <h4><u>Comments:</u></h4>
            <p>test</p>
            <ul>
               {% for comment in text %}
               <p>Posted by:{{comment.user.first_name}}</p>
               <li>{{comment}}</li>
               <a href="commentDelete/commentDelete/{{comment.id}}">Delete Comments</a>
               {% endfor %}
            </ul>
         </div>

         <div class="row">
            <div class="buttons col">
               <a href="{% url 'course:index' %}"><button type="button" name="button">Back To Courses</button></a>
               <form class="" action="commentPost/{{course.id}}" method="post">
                  {% csrf_token %}
                  <textarea name="comment" rows="8" cols="80"></textarea>
                  <input type="submit" name="" value="Add Comment To Course">
               </form>
            </div>
         </div>
         {% endfor %}
      </div>
   </body>
</html>

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/templates/courseapp/remove.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>Remove</title>
      {% load staticfiles %}
      <link rel="stylesheet" href="{% static 'courseapp/css/bootstrap.css' %}">
      <link rel="stylesheet" href="{% static 'courseapp/css/style.css' %}">
   </head>
   <body>

      <div class="container">
         <div class="row">
            <div class="header col">
               <h3>Are you Sure You Want To Remove The Course?</h3>
               {% for id in ids %}
               <ul>
                  <h5>Name: {{id.name}} </h5>
                  <h5>Description: {{id.description}} </h5>
               </ul>
            </div>
         </div>
         <div class="row">
            <div class="buttons col">
               <a href="{% url 'course:index' %}"><button type="button" name="button">No</button></a>
               <form class="" action="delete/remove/{{id.id}}" method="post">
                  {% csrf_token %}
                  <input type="submit" name="delete" value="Yes I want to delete this!">
               </form>
            </div>
         </div>
         {% endfor %}
      </div>
   </body>
</html>

Python/PythonII/DjangoII/Multi_Apps/apps/courseapp/templates/courseapp/user_courses.html
<!DOCTYPE html>
<html>
   <head>
      <meta charset="utf-8">
      <title>User Courses</title>
   </head>
   <body>
      <div class="container">
         <div class="row">
            <div class="">
               <h3><u>User: Info</u></h3>
               <h5>Name: {{request.session.name}} {{request.session.last}}</h5>
               <h5>Email: {{request.session.email}}</h5>
            </div>
         </div>
         <div class="row">
            <div class="form-inline col">
               <form class="user_courses" action="{% url 'course:add_user_courses' %}" method="post">
                  {% csrf_token %}
                  <select class="users" name="student">
                     <option value="Users">Users</option>
                     {% for user in users %}
                     <option value="{{user.user.email}}">{{user.user.email}}</option>
                     {% endfor %}
                  </select>
                  <select class="courses" name="class">
                     <option value="Courses">Courses</option>
                     {% for course in users %}
                     <option value="{{course.name}}">{{course.name}}</option>
                     {% endfor %}
                  </select>
                  <button type="submit" name="button">Add User to Course</button>
               </form>
            </div>

         </div>
         <div class="row">
            <div class=" col">
               <table class="table table-bordered">
                  <thead>
                     <th>Course</th>
                     <th>Title</th>
                     <th>Number of Users</th>
                  </thead>
                  {% for data in users %}
                  <tr>
                     <td>{{data.id}}</td>
                     <td>{{data.name}}</td>
                     <td>{{data.count}}</td>
                     {% endfor %}
                  </tr>
               </table>
            </div>
         </div>
         <a href="{% url 'login:success' %}">Return Home</a>
      </div>
   </body>
</html>